Documentation and Travis Changes

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,39 +1,108 @@
+sudo: false
+dist: trusty
 language: php
-
 notifications:
   email:
     on_success: never
     on_failure: change
-
-php:
-  - 5.6
-  - 7
-
+cache:
+  directories:
+    - vendor
+    - $HOME/.composer/cache
 after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
-
 env:
   matrix:
-    - WP_VERSION=latest WP_MULTISITE=0
-    - WP_VERSION=nightly WP_MULTISITE=0
-
+  - WP_VERSION=latest WP_MULTISITE=0
   global:
+  - WP_TRAVISCI=travis:phpunit
     - SVN_REPO: https://plugins.svn.wordpress.org/semantic-linkbacks/
     - GH_REF: https://github.com/pfefferle/wordpress-semantic-linkbacks.git
-    - secure: "4WcaCZP5VsKAYGvSZUR0vLIwzyU6qZ4VyAuMTZWJ9A/08MJtI81WJy355URU/HC5Jwt9qQ8ZyPOSpwo0XNaJsd/emqr5OsC3X1yaAn9lnfS+X8jdjRDsC5nWXGPb0KyX/hzVMtO2rxwo4k9WYdSEVz8m/iD0P8MIWOF5d1CS6ifBZ5HPiCh2s9okEdy4hnR78cEJXBgSR6jmxHSBKgzkR2otiuccy4ZoNk/050i5aRtLZFT4rgxAwqwzodUgOpq867V7hXw9MHfYRgwS1kRyZcst4YkVHPu8rXlhjKHLuVApHqyn5QYkqnBZuPA1ID+/7FEQn46F/EEiZXVO/RHe0Egq4gZdEHyqtjou4jjKhEgQAeEnlVPLI+8GmmYuls1YtXJsFMCGc8zlWMTlNIz+qjmJl1RxXM7fwC7OhXfvUqkFnT8KA+HeAeje1yOzIzyysXAqCFsfST81l/CtH4YyUwXHR1io+Qo9UErEWoW0UtJkoK7OxkF4Bb6UzJQ5qZSU6OYBIghjMHaiwyu4+27UL5JRZRDfoRmxqz4KqSfsDL/97qsm6/F8a6hqf5IIK2kDKSyedZGED6t1WDotstcB7bXlhYgLv5be+Uselc0etMypcYzAvfkebDLCqKp+b9BEKJ4mT+K0VneeU9IKBRovMUSo6AHbChJtVQFTl580ODE="
-
+    - secure: "4WcaCZP5VsKAYGvSZUR0vLIwzyU6qZ4VyAuMTZWJ9A/08MJtI81WJy355URU/HC5Jwt9qQ8ZyPOSpwo0XNaJsd/emqr5OsC3X1yaAn9lnfS+X8jdjRDsC5nWXGPb0KyX/hzVMtO2rxwo4k9WYdSEVz8m/iD0P8MIWOF5d1CS6ifBZ5HPiCh2s9okEdy4hnR78cEJ
+XBgSR6jmxHSBKgzkR2otiuccy4ZoNk/050i5aRtLZFT4rgxAwqwzodUgOpq867V7hXw9MHfYRgwS1kRyZcst4YkVHPu8rXlhjKHLuVApHqyn5QYkqnBZuPA1ID+/7FEQn46F/EEiZXVO/RHe0Egq4gZdEHyqtjou4jjKhEgQAeEnlVPLI+8GmmYuls1YtXJsFMCGc8zlWMTlNIz+qjm
+Jl1RxXM7fwC7OhXfvUqkFnT8KA+HeAeje1yOzIzyysXAqCFsfST81l/CtH4YyUwXHR1io+Qo9UErEWoW0UtJkoK7OxkF4Bb6UzJQ5qZSU6OYBIghjMHaiwyu4+27UL5JRZRDfoRmxqz4KqSfsDL/97qsm6/F8a6hqf5IIK2kDKSyedZGED6t1WDotstcB7bXlhYgLv5be+Uselc0etM
+ypcYzAvfkebDLCqKp+b9BEKJ4mT+K0VneeU9IKBRovMUSo6AHbChJtVQFTl580ODE="
 matrix:
   include:
-    - php: 5.6
-      env: WP_VERSION=latest WP_MULTISITE=0 WP_PULUGIN_DEPLOY=1
-
+  - php: 7.2
+  - php: 7.1
+  - php: 7.0
+  - php: 5.6
+  - php: 5.6
+    env: WP_PULUGIN_DEPLOY=1
+  - php: 5.5
+  - php: 5.4
+  - php: 5.3
+    dist: precise
 before_script:
-  - export PATH="$HOME/.composer/vendor/bin:$PATH"
-  - |
-    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
-      composer global require "phpunit/phpunit=5.7.*"
-    elif [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
-      composer global require "phpunit/phpunit=4.8.*"
-    fi
-  - bash bin/install-wp-tests.sh wordpress root '' localhost $WP_VERSION
+- |
+  # Remove Xdebug for a huge performance increase:
+  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
+    phpenv config-rm xdebug.ini
+  else
+    echo "xdebug.ini does not exist"
+  fi
+- |
+  # Export Composer's global bin dir to PATH:
+  composer config --list --global
+  export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
+- |
+  # Install the specified version of PHPUnit depending on the PHP version:
+  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
+    case "$TRAVIS_PHP_VERSION" in
+      7.2|7.1|7.0|nightly)
+        echo "Using PHPUnit 6.x"
+        composer global require "phpunit/phpunit:^6"
+        ;;
+      5.6|5.5|5.4|5.3)
+        echo "Using PHPUnit 4.x"
+        composer global require "phpunit/phpunit:^4"
+        ;;
+      5.2)
+        # Do nothing, use default PHPUnit 3.6.x
+        echo "Using default PHPUnit, hopefully 3.6"
+        ;;
+      *)
+        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
+        exit 1
+        ;;
+    esac
+  fi
+  if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
+      composer install
+  fi
 
-script: phpunit
+- mysql --version
+- phpenv versions
+- php --version
+- php -m
+- which phpunit
+- phpunit --version
+- curl --version
+- grunt --version
+- git --version
+- svn --version
+- locale -a
+before_install:
+- export PATH="$HOME/.composer/vendor/bin:$PATH"
+- |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      set -e
+      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
+      set +e
+    fi
+script:
+  - |
+    if [[ ! -z "$WP_VERSION" ]] ; then
+      # Run the build because otherwise there will be a bunch of warnings about
+      # failed `stat` calls from `filemtime()`.
+      echo Running with the following versions:
+      php -v
+      phpunit --version
+      # Run PHPUnit tests
+      phpunit || exit 1
+      WP_MULTISITE=1 phpunit || exit 1
+    fi
+  - |
+    if [[ "$WP_TRAVISCI" == "travis:phpcs" ]] ; then
+      ./vendor/bin/phpcs -p -s -v -n --standard=./phpcs.ruleset.xml --extensions=php
+    fi
